services:

  web:
    container_name: flask_test
    image: flask_web
    build: ./src
    entrypoint: ["pytest"] # override entrypoint
    command: ["test/", "-v"] #run pytest
    env_file:
      - .env.example
